FROM python:3.12.2-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY requirements-bot.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements-bot.txt
COPY crypto-bot.py .
COPY xstock-bot.py .
